### PR TITLE
Refactor delay logic and redundant attributes

### PR DESCRIPTION
**Pull request by adhes14**

### CODE REVIEW

**Comment by Dru27** [comment]
Good job! remove the comments of Main.java, please

**Review by Dru27 — DISMISSED** [review]

**Comment by adhes14** [comment]
Ok. I'll do it

**Comment by Agustin-Mediotti** [comment]
Excellent! we  need to remove all commented code

**Review by adrianovi — APPROVED** [review]
Good job Adhemar, I agree with my partners about removing the commented code

**Comment by alvarogerardo007** [comment]
Good JOb!!

**Pull request merged**
