### PR TITLE
Adrian/spaceinvaders

### PR DESCRIPTION
**Pull request by adrianovi**

### CODE REVIEW

**Review by dulphyj — APPROVED** [review]

**Review by Dru27 — APPROVED** [review]

**Review by alvarogerardo007 — APPROVED** [review]
good Job!!

**Comment by Dru27** [comment]
Looks good!

**Comment by dulphyj** [comment]
great job

**Comment by Agustin-Mediotti** [comment]
This class will be a child of Sprite, so consider `public class Ship extends Sprite`

**Pull request merged**
